DEFAULT_SEED = 42
LEARNING_RATE = 0.0001
MINIBATCH_SIZE = 100
REPLAY_BUFFER_SIZE = int(1e5)
DISCOUNT_FACTOR = 0.99
EPSILON_START = 1.0
EPSILON_MIN = 0.01
EPSILON_DECAY_PORTION = 0.5
TARGET_UPDATE_EVERY = 4
EPSYLON_TYPE = {
    1: "lineare",
    2: "esponenziale"
}
EPSYLON_IS = 1