DEFAULT_TRAIN_EPISODES = 1000
DEFAULT_TEST_DELAY = 0.1
STEP_LIMIT = 1000
SCORES_WINDOW_SIZE = 100
SAVE_CHECKPOINT_EVERY = 100
DEFAULT_MODEL_FILENAME = "best_model.pth"
DEFAULT_GRAPH_FILENAME = "grafico_finale.png"