# -*- coding: utf-8 -*-
"""Copia di Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEogmwI2KJ3qI6I3IDKfRrBrnMlifPWB
"""

import gymnasium as gym
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import pygame
import time
import os
import random
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd as autograd
from torch.autograd import Variable
from collections import deque, namedtuple
from tqdm import tqdm


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

def argwhere(matrix, value):
  l = list()
  x_max,y_max=matrix.shape
  for x in range(x_max):
    for y in range(y_max):

      if matrix[x,y] == value:
        l.append([x,y])

  return l

def creaMatriceDistanze( nomeFile, direzione):
  df = pd.read_csv(nomeFile,
                   #sep = ';',
                   header = None)
  matrice_distanze = df.to_numpy()
  traguardo = argwhere(matrice_distanze,2)

  larghezza, altezza=matrice_distanze.shape

  for x in range(larghezza):
    for y in range(altezza):
      if matrice_distanze[x,y] != -1:
        matrice_distanze[x,y] = -2

  a = matrice_distanze






  index = traguardo.copy() #secondo me ha più senso calcolare la distanza dalla prima cella del traguardo disponibile rispetto ad una (list([[35,50]]))


  for i in index:
    a[i[0],i[1]] = 0





  match direzione:
    case "destra":
      slider=[0,1]
    case "sinistra":
      slider=[0,-1]
    case "basso":
      slider=[1,0]
    case "alto":
      slider=[-1,0]
    case _:
      slider=[0,0]


  for i in index:
    i[0]=i[0]+slider[0]
    i[1]=i[1]+slider[1]
    a[i[0],i[1]]=1
  print(f"linea iniziale {index}")

  while len(index) != 0:
      i = index.pop(0)
      #bisogna capire come non fare andare all'indietro del traguardo
      if (i[1]-1) >= 0 and a[i[0],i[1]-1] == -2 and traguardo.count([i[0],i[1]-1]) == 0:
          a[i[0],i[1]-1] = a[i[0],i[1]]+1
          index.append([i[0],i[1]-1])

      if (i[1]+1) < altezza and a[i[0],i[1]+1] == -2  and traguardo.count([i[0],i[1]+1]) == 0:
          a[i[0],i[1]+1] = a[i[0],i[1]]+1
          index.append([i[0],i[1]+1])

      if (i[0]-1) >= 0 and a[i[0]-1,i[1]] == -2  and traguardo.count([i[0]-1,i[1]]) == 0:
          a[i[0]-1,i[1]] = a[i[0],i[1]]+1
          index.append([i[0]-1,i[1]])

      if (i[0]+1) < larghezza and a[i[0]+1,i[1]] == -2  and traguardo.count([i[0]+1,i[1]]) == 0:
          a[i[0]+1,i[1]] = a[i[0],i[1]]+1
          index.append([i[0]+1,i[1]])

  # 2. Convertiamo in DataFrame
  df = pd.DataFrame(a)

  # 3. Salviamo in CSV
  df.to_csv('mio_file.csv', index=False, header=False)

  return a


def count_numpy_list(list_numpy, param):
  cont = 0
  for x in list_numpy:
    if x[0] == param[0] and x[1] == param [1]:
      cont = cont + 1

  return cont

class TrackEnv(gym.Env):



  

  def __init__(self, render_mode=None): 
      
        # Metadati per il rendering (es. 10 FPS per vederlo con calma)
        self.metadata = {"render_fps": 10, "render_modes": ["human", "rgb_array"]}
        
        self.matrix = buildTrack()
        self.distance_matrix = creaMatriceDistanze(os.getcwd() + "/data/tracks/track_imola.csv", "destra")
        
        # --- VARIABILI PER IL RENDERING ---
        self.render_mode = render_mode
        self.window_size = 800  # Dimensione della finestra in pixel
        self.window = None      # Finestra Pygame
        self.clock = None       # Clock per gestire gli FPS
        # ----------------------------------

        self.view_size = 7
        self.road_width = 5
        self.trajectory = list()

        coordinates = np.argwhere(self.matrix == 2)
        self._target_location = np.array(coordinates, dtype=np.int32)
        self._agent_location = np.array(coordinates[self.road_width // 2], dtype=np.int32)
        #self._agent_velocity = 1

        self.action_space = gym.spaces.Discrete(4)
        
        self._action_to_direction = {
            0: np.array([0, 1]),
            1: np.array([-1, 0]),
            2: np.array([0, -1]),
            3: np.array([1, 0]),
        }

        self.observation_space = gym.spaces.Dict({  #i dict servono per spazi eterogenei
                # 1. La sottomatrice locale (come prima)
                "agent_view": gym.spaces.Box( #i box servono per spazi omogenei
                    low=-2,
                    high=2,
                    shape=(self.view_size, self.view_size),
                    dtype=np.int8
                )
                #,

                # 2. La direzione (angolo in radianti o gradi)
                # Definiamo un array di shape=(1,) contenente un float
                # Esempio: da 0 a 2*PI (circa 6.28)
                #"direction": gym.spaces.Box(
                #    low=0,
                #    high=2 * math.pi,
                #    shape=(1,),
                #    dtype=np.float32
                #),

                #aggiungere velocità
                #"velocity": gym.spaces.Box(
                #    low=0,
                #   high=self.matrix.shape[0],
                #   shape=(1,),
                #   dtype=np.float32
                #)
            })

        self._checkpoints = dict()
        self.numero_checkpoints=7

        valore_checkpoint=self.distance_matrix.max()//self.numero_checkpoints
        for i in range(self.numero_checkpoints-1):
           
            #print(f"valore checkpoint n.{i} = {valore_checkpoint*(i+1)}")
            coordinate_checkpoint=argwhere(self.distance_matrix, valore_checkpoint*(i+1))
            self._checkpoints[f"checkpoint_{i+1}"] = coordinate_checkpoint

        #print(self._checkpoints)

        self._progresso = 0




  def _get_obs(self):
    view_padding = self.view_size // 2
    max_x,max_y = self.matrix.shape

    # HO CAMBIAMO IL LOW DELLO SPAZIO DELLE OSSERVAZIONI DA -1 A -2 PERCHè SERVE
    # UN MODO PER INDICARE UNA CELLA CHE NON ESISTE

    # creo la matrice che vede il pilota
    view_matrix = np.ones(shape=(self.view_size, self.view_size))
    # inizializzo tutte le celle viste dal pilota come non esistenti
    for i in range(self.view_size):
      view_matrix[i]=view_matrix[i]*-2
    #indice della prima cella (top-left) della matrice della vista pilota nella matrice grande
    tl_x = self._agent_location[0] - view_padding
    tl_y = self._agent_location[1] - view_padding

    view_matrix_x = range(tl_x, tl_x+self.view_size,1)
    view_matrix_y = range(tl_y, tl_y+self.view_size,1)

    #tengo soltanto gli indici interni alla matrice grande
    clipped_view_matrix_x = np.clip(view_matrix_x,0, max_x - 1)
    clipped_view_matrix_y = np.clip(view_matrix_y,0, max_y - 1)
    #rimuovo i duplicati creati da np.clip
    clipped_view_matrix_x = list(set(clipped_view_matrix_x))
    clipped_view_matrix_y = list(set(clipped_view_matrix_y))

    #copio i valori dalla matrice grande in quella della visione del pilota
    for x in clipped_view_matrix_x:
      for y in  clipped_view_matrix_y:
        view_matrix[x-tl_x , y-tl_y]=self.matrix[y,x]

    view_matrix = view_matrix.T


    return { "agent_view": view_matrix 
            #"direction": self._agent_direction,
            # "velocity":self._agent_velocity
            }





  #come info restituiamo la posizione e direzione del pilota
  def _get_info(self):
    return { "agent_location":self._agent_location
            #,"agent_direction":self._agent_direction,
             #"agent_velocity":self._agent_velocity
             }



  #con reset, rimettiamo il pilora nella posizione iniziale dal traguard
  # e ristabiliamo la sua direzione
  def reset(self, seed = None, options = None):

    super().reset(seed=seed)

   # self._agent_direction = math.pi

    #self._agent_velocity = 1

    self._progresso = 0

    coordinates = np.argwhere(self.matrix == 2)

    #da cambiare
    self._agent_location = np.array(coordinates[self.road_width // 2], dtype = np.int32)


    observation = self._get_obs()
    info = self._get_info()
    return observation, info







  def step(self, action):

    size = self.matrix.shape[0]
    direction = self._action_to_direction[action]

        # Update agent position, ensuring it stays within grid bounds
        # np.clip prevents the agent from walking off the edge
    self._agent_location = np.clip(
            self._agent_location + direction, 0, size - 1
        )


    self.trajectory.append(self._agent_location)
        # Check if agent reached the target
    terminated=False
    #for x in self._target_location:
     #   if np.array_equal(x, self._agent_location):
    #       print("--------------------")
     #       terminated = True

        # We don't use truncation in this simple environment
        # (could add a step limit here if desired)
    truncated = False


    # traguardo si attiva quando tutti i checkpoint sono stati traversati
    # se il tragurdo è traversato prima gli diamo un reward negativo assurdo


    # da aggingere logica reward negativo fuori strada
    '''stavo pensando se invece non é meglio terminare la simulazione se va fuori. Altrimenti se la continuiamo lui raccoglie dati su come guidare
    fuori dal tracciato e nella migliore delle ipotesi al massimo imparerebbe come rientrare in pista. Solo che il nostro obiettivo é che non esca proprio
    quindi aggiungerei un
    '''

    if self.matrix[self._agent_location[0],self._agent_location[1]] == -1:
        reward = -1000
        truncated = True
    
    else:
        #reward = self.distance_matrix[self._agent_location[0],self._agent_location[1]]

        for x in self._checkpoints[f"checkpoint_{self._progresso+1}"]:
            
            if np.array_equal(self._agent_location,x):
                reward = 1000
                self._progresso=self._progresso+1
            else:
                reward = -1


    '''
    #1. reward = -1 costante + bonus checkpoint

    checkpoint pensavo di rappresentarlo con un dizionario {id_numerico: [stato, [riga1, colonna1], [riga2, colonna2], [riga3, colonna3]...]}
    dove stato indica se il checkpoint é 0 = da prendere, 1 = giá preso e 2 = attivo (se li vogliamo attivare sequenzialmente come avevamo detto)

    if checkpoint_taken(self._agent_location, checkpoint_list) == 2: < metodo da scrivere, prende la lista di checkpoint e controlla se l'agente si trova
                                                                  sopra checkpoint attivo, ritorna 2 se tutto OK, 1 se passa su checkpoint giá preso, 0 altrimenti
       reward = 10
    else:
       reward = -1
    _______________________________________________________________________________________________

    #2. reward = -(distanza_massima - distanza) costante checkpoint 2 volte -> reward negativo

        reward = -(self.distance_matrix.max() - self.distance_matrix[self._agent_location[0],self._agent_location[1]])
        if checkpoint_taken(self._agent_location, checkpoint_list) == 1:
          reward = -5






    # reward = -( numero_reward_traguardo - distnza) costante + logica checkpoint
    # reward =
    '''
    observation = self._get_obs()
    info = self._get_info()

    return observation, reward, terminated, truncated, info





    return 0



  def render(self):
      if self.render_mode == "rgb_array":
          return self._render_frame()
      elif self.render_mode == "human":
          return self._render_frame()

  def _render_frame(self):
      if self.window is None and self.render_mode == "human":
          pygame.init()
          pygame.display.init()
          self.window = pygame.display.set_mode((self.window_size, self.window_size))
      
      if self.clock is None and self.render_mode == "human":
          self.clock = pygame.time.Clock()

      canvas = pygame.Surface((self.window_size, self.window_size))
      canvas.fill((0, 0, 0)) # Sfondo nero di base

      # Calcolo della dimensione di ogni cella
      # Prendiamo il lato più lungo della matrice per scalare tutto nella finestra quadrata
      max_dim = max(self.matrix.shape)
      pix_square_size = self.window_size / max_dim

      # --- DISEGNO DELLA PISTA ---
      rows, cols = self.matrix.shape
      for r in range(rows):
          for c in range(cols):
              val = self.matrix[r, c]
              
              # Determina il colore in base al valore nella matrice
              color = None
              if val == 2:
                  color = (255, 0, 0)      # Rosso per il traguardo
              elif val == 0:                
                  color= (255,255,255)      #Bianco per i cordoli
              elif val == 1:
                  color = (128, 128, 128)  # Grigio per la strada
              else:
                  color = (34, 139, 34)    # Verde scuro per fuori strada (-1, -2)

              if color:
                  pygame.draw.rect(
                      canvas,
                      color,
                      pygame.Rect(
                          c * pix_square_size, # x (colonna)
                          r * pix_square_size, # y (riga)
                          pix_square_size,
                          pix_square_size,
                      ),
                  )

      # --- DISEGNO DELL'AGENTE ---
      # L'agente è un cerchio blu
      pygame.draw.circle(
          canvas,
          (0, 0, 255), # Blu
          (int((self._agent_location[1] + 0.5) * pix_square_size), # X = colonna
          int((self._agent_location[0] + 0.5) * pix_square_size)), # Y = riga
          int(pix_square_size / 3),
      )

      if self.render_mode == "human":
          self.window.blit(canvas, canvas.get_rect())
          pygame.event.pump()
          pygame.display.update()
          self.clock.tick(self.metadata["render_fps"])
      else:  # rgb_array
          return np.transpose(
              np.array(pygame.surfarray.pixels3d(canvas)), axes=(1, 0, 2)
          )













def buildTrack(fileName = os.getcwd() + "/data/tracks/track_imola.csv"):
  df = pd.read_csv(fileName, header = None
                   #,sep=';'
                   )
  matrice_circuito = df.to_numpy()
  print(f"Dimensioni matrice:{matrice_circuito.shape}")
  #print(matrice_circuito)
  return matrice_circuito



class Network(nn.Module):
    def __init__(self, input_dim, action_size, seed=42):
        super(Network, self).__init__()
        self.seed = torch.manual_seed(seed)
        
        # input_dim sarà la somma di tutte le feature (es. 49 per ora)
        self.fc1 = nn.Linear(input_dim, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, action_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

class ReplayBuffer:
    def __init__(self, capacity, batch_size, seed=42):
        self.memory = deque(maxlen=capacity)
        self.batch_size = batch_size
        self.seed = random.seed(seed)

    def add(self, state, action, reward, next_state, done):
        # Salviamo tutto come numpy array o semplici float
        self.memory.append((state, action, reward, next_state, done))

    def sample(self):
        batch = random.sample(self.memory, self.batch_size)
        # Scompattiamo il batch
        states, actions, rewards, next_states, dones = zip(*batch)
        return states, actions, rewards, next_states, dones

    def __len__(self):
        return len(self.memory)

class Agent:
    def __init__(self, view_size, action_size, number_episodes, seed=42):

        learning_rate = 5e-3
        minibatch_size = 100
        replay_buffer_size = int(1e5)

        self.action_size = action_size
        self.view_size = view_size
        
        # Calcoliamo la dimensione totale dell'input appiattito
        self.input_dim = view_size * view_size 
        
        # Spostiamo le reti sul DEVICE corretto
        self.q_net = Network(self.input_dim, action_size, seed).to(DEVICE)
        self.target_net = Network(self.input_dim, action_size, seed).to(DEVICE)
        self.target_net.load_state_dict(self.q_net.state_dict())
        self.target_net.eval()
        
        self.optimizer = optim.Adam(self.q_net.parameters(), lr=learning_rate)
        self.memory = ReplayBuffer(capacity=replay_buffer_size, batch_size=minibatch_size, seed=seed)
        
        self.gamma = 0.99   # discount factor
        self.epsilon = 1.0
        self.epsilon_min = 0.01
        self.epsilon_decay = 1/(number_episodes*0.5)
        self.t_step = 0

    def _preprocess_state(self, state_dict):
        """
        Prende un dizionario (o lista di dizionari) ed estrae/appiattisce i dati
        in un unico array numpy o tensore.
        """
        if isinstance(state_dict, dict):
            view = state_dict["agent_view"]
            return view.flatten()
            
        elif isinstance(state_dict, (list, tuple)):
            batch_views = [s["agent_view"] for s in state_dict]
            return np.array(batch_views).reshape(len(batch_views), -1)

    def update_epsilon(self):
        self.epsilon = max(self.epsilon_min, self.epsilon - self.epsilon_decay)
        return self.epsilon

    def select_action(self, state):
        # 1. Preprocess: estrae e appiattisce -> (49,)
        processed_state = self._preprocess_state(state)
        
        # 2. Trasforma in Tensor, aggiungi batch dim -> (1, 49) E SPOSTA SU DEVICE
        # AGGIUNTO .to(DEVICE) QUI SOTTO
        state_t = torch.from_numpy(processed_state).float().unsqueeze(0).to(DEVICE)
        
        self.q_net.eval()
        with torch.no_grad():
            action_values = self.q_net(state_t)
        self.q_net.train()

        if random.random() > self.epsilon:
            return np.argmax(action_values.cpu().data.numpy()) # .cpu() serve per portarlo fuori dalla GPU se necessario
        else:
            return random.choice(np.arange(self.action_size))

    def step(self, state, action, reward, next_state, done):
        self.memory.add(state, action, reward, next_state, done)
        
        self.t_step = (self.t_step + 1) % 4
        if self.t_step == 0:
            if len(self.memory) > self.memory.batch_size:
                self.learn()

    def learn(self):
        states, actions, rewards, next_states, dones = self.memory.sample()

        # 1. Preprocessiamo il batch
        states_np = self._preprocess_state(states)
        next_states_np = self._preprocess_state(next_states)

        # 2. Conversione in Tensor E SPOSTAMENTO SU DEVICE
        # AGGIUNTO .to(DEVICE) A TUTTI I TENSORI
        states_t = torch.tensor(states_np).float().to(DEVICE)
        next_states_t = torch.tensor(next_states_np).float().to(DEVICE)
        
        actions_t = torch.tensor(actions).long().unsqueeze(1).to(DEVICE)
        rewards_t = torch.tensor(rewards).float().unsqueeze(1).to(DEVICE)
        dones_t = torch.tensor(dones).float().unsqueeze(1).to(DEVICE)

        # --- Calcolo della loss ---
        q_expected = self.q_net(states_t).gather(1, actions_t)
        
        with torch.no_grad():
            q_next = self.target_net(next_states_t).detach().max(1)[0].unsqueeze(1)
            q_target = rewards_t + (self.gamma * q_next * (1 - dones_t))
        
        loss = F.mse_loss(q_expected, q_target)
        
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

def save_training_plot(scores, filename="training_plot.png", window_size=50):
    """
    Crea e salva un grafico dell'andamento dei reward.
    
    Args:
        scores (list): La lista completa dei punteggi per ogni episodio.
        filename (str): Il percorso dove salvare l'immagine.
        window_size (int): L'ampiezza della finestra per la media mobile.
    """
    # Imposta la dimensione della figura
    plt.figure(figsize=(10, 6))
    
    
    # 2. Calcolo e Plot della Media Mobile (Trend)
    # Se abbiamo abbastanza dati per calcolare la media
    if len(scores) >= window_size:
        # Calcola la media mobile usando la convoluzione (molto veloce)
        moving_avg = np.convolve(scores, np.ones(window_size)/window_size, mode='valid')
        
        # L'asse X per la media mobile deve essere spostato per allinearsi
        # (parte dall'episodio 'window_size')
        x_axis = np.arange(window_size - 1, len(scores))
        
        plt.plot(x_axis, moving_avg, color='blue', linewidth=2, label=f'Media Mobile ({window_size} ep)')

    # Etichette e Titolo
    plt.title('Andamento Addestramento DQN')
    plt.xlabel('Episodio')
    plt.ylabel('Reward Totale (Score)')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    
    # Salva il file
    plt.savefig(filename)
    print(f"Grafico salvato in: {filename}")
    
    # Chiudi la figura per liberare memoria
    plt.close()


def training(number_episodes):
    env = TrackEnv(render_mode="human")
    state_shape = env.observation_space["agent_view"].shape

    state_size = env.observation_space["agent_view"].shape[0]
    number_actions = env.action_space.n
    print('State shape: ', state_shape)
    print('State size: ', state_size)
    print('Number of actions: ', number_actions)

    interpolation_parameter = 1e-3
    step_limit = 1000
    step_count=0

    pilota = Agent(state_size, number_actions, number_episodes)

    # Liste per tenere traccia dei punteggi
    scores = []
    scores_window = [] # Per la media mobile (es. ultimi 100 episodi)

    # Loop principale
    loop = tqdm(range(number_episodes))

    for i_episode in loop:
        state, _ = env.reset()
        score = 0 # Punteggio dell'episodio corrente
        step_count = 0

        terminated = False
        truncated = False

        while not (terminated or truncated) and step_count < step_limit:

            # 1. Scelta Azione
            action = pilota.select_action(state)

            # 2. Step nell'ambiente
            next_state, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated

            
            

            # 3. Addestramento (Memorizza e impara)
            pilota.step(state, action, reward, next_state, done)

            # 4. Aggiornamento variabili
            state = next_state
            score += reward
            step_count += 1

        # --- Fine Episodio ---
        pilota.update_epsilon()

        # Salviamo i punteggi
        scores.append(score)
        scores_window.append(score)
        if len(scores_window) > 100: scores_window.pop(0) # Teniamo solo gli ultimi 100

        # Aggiorniamo la barra di caricamento con le info utili
        loop.set_description(f"Ep: {i_episode+1} | Score: {score:.2f} | Avg Score: {np.mean(scores_window):.2f} | Epsilon: {pilota.epsilon:.3f}")

        # (Opzionale) Salviamo il modello se otteniamo un buon risultato o ogni 100 episodi
        if (i_episode + 1) % 100 == 0:
            torch.save(pilota.q_net.state_dict(), f'checkpoint_ep_{i_episode+1}.pth')

    save_training_plot(scores, filename="grafico_finale.png")

    env.close()

def test_model(model_path, num_episodes=5, delay=0.1):
    """
    Carica un modello addestrato e lo visualizza in azione.
    
    Args:
        model_path (str): Il percorso del file .pth (es. 'checkpoint_ep_500.pth')
        num_episodes (int): Quanti episodi di test vuoi vedere.
        delay (float): Secondi di pausa tra un frame e l'altro (per rallentare l'azione).
    """
    
    # 1. Controlla se il file esiste
    if not os.path.exists(os.getcwd() + "/models/checkpoints/"+model_path):
        print(f"ERRORE: Il file '{model_path}' non esiste.")
        return

    print(f"Caricamento modello da: {model_path}...")

    # 2. Crea l'ambiente in modalità 'human' per il rendering
    #    Nota: view_size deve essere uguale a quello usato in training (7)
    env_test = TrackEnv(render_mode="human")
    
    view_size = 7 
    action_size = env_test.action_space.n

    # 3. Istanzia l'agente (la struttura deve essere IDENTICA a quella del training)
    #    Non ci serve la memoria o l'optimizer qui, ma la classe Agent li crea comunque.
    pilota_test = Agent(view_size, action_size, 1)

    # 4. Carica i pesi nella rete (q_net)
    #    map_location='cpu' serve se hai addestrato su GPU ma testi su CPU
    pilota_test.q_net.load_state_dict(torch.load(model_path,weights_only=True, map_location=torch.device(DEVICE)))
    
    # Imposta la rete in modalità valutazione (disattiva dropout, batchnorm, ecc.)
    pilota_test.q_net.eval() 

    # 5. Imposta Epsilon a 0 -> Solo sfruttamento (Exploitation), niente esplorazione
    pilota_test.epsilon = 0.0

    step_limit = 1000

    # --- CICLO DI TEST ---
    for i in range(num_episodes):
        state, _ = env_test.reset()
        score = 0
        step = 0
        done = False
        
        print(f"\n--- Inizio Episodio di Test {i+1} ---")
        
        while not done:
            # Renderizza la scena
            env_test.render()
            
            # Scegli l'azione (sarà sempre la migliore secondo la rete)
            action = pilota_test.select_action(state)
            
            # Esegui l'azione
            next_state, reward, terminated, truncated, _ = env_test.step(action)
            
            done = terminated or truncated
            state = next_state
            score += reward
            step += 1
            
            # Rallenta un po' per permettere all'occhio umano di seguire
            time.sleep(delay)
            
            # Sicurezza per evitare loop infiniti se l'agente si blocca
            if step > step_limit:
                print("Loop troppo lungo, interrompo episodio.")
                break

        print(f"Episodio {i+1} terminato. Punteggio Totale: {score:.2f}")

    env_test.close()
    print("Test completato.")


#training(10000) models\checkpoints\checkpoint_ep_60000.pth
test_model("checkpoint_ep_60000.pth")